# python train_fixed_gs.py --config_path 'config/pacnerf/newtonian/default.json' --model_path 'output/pacnerf/newtonian/0' --source_path '/home/qingran/Desktop/gic/data/pacnerf/newtonian/0' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/newtonian/0/0.ply
# python train_fixed_gs.py --config_path 'config/pacnerf/newtonian/default.json' --model_path 'output/pacnerf/newtonian/1' --source_path '/home/qingran/Desktop/gic/data/pacnerf/newtonian/1' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/newtonian/1/0.ply
# python train_fixed_gs.py --config_path 'config/pacnerf/newtonian/default.json' --model_path 'output/pacnerf/newtonian/2' --source_path '/home/qingran/Desktop/gic/data/pacnerf/newtonian/2' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/newtonian/2/0.ply
# python train_fixed_gs.py --config_path 'config/pacnerf/newtonian/default.json' --model_path 'output/pacnerf/newtonian/3' --source_path '/home/qingran/Desktop/gic/data/pacnerf/newtonian/3' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/newtonian/3/0.ply
# python train_fixed_gs.py --config_path 'config/pacnerf/newtonian/default.json' --model_path 'output/pacnerf/newtonian/4' --source_path '/home/qingran/Desktop/gic/data/pacnerf/newtonian/4' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/newtonian/4/0.ply
# python train_fixed_gs.py --config_path 'config/pacnerf/newtonian/default.json' --model_path 'output/pacnerf/newtonian/5' --source_path '/home/qingran/Desktop/gic/data/pacnerf/newtonian/5' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/newtonian/5/0.ply
# python train_fixed_gs.py --config_path 'config/pacnerf/newtonian/default.json' --model_path 'output/pacnerf/newtonian/6' --source_path '/home/qingran/Desktop/gic/data/pacnerf/newtonian/6' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/newtonian/6/0.ply
# python train_fixed_gs.py --config_path 'config/pacnerf/newtonian/default.json' --model_path 'output/pacnerf/newtonian/7' --source_path '/home/qingran/Desktop/gic/data/pacnerf/newtonian/7' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/newtonian/7/0.ply
# python train_fixed_gs.py --config_path 'config/pacnerf/newtonian/default.json' --model_path 'output/pacnerf/newtonian/8' --source_path '/home/qingran/Desktop/gic/data/pacnerf/newtonian/8' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/newtonian/8/0.ply
# python train_fixed_gs.py --config_path 'config/pacnerf/newtonian/default.json' --model_path 'output/pacnerf/newtonian/9' --source_path '/home/qingran/Desktop/gic/data/pacnerf/newtonian/9' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/newtonian/9/0.ply

python train_fixed_gs.py --config_path 'config/pacnerf/non_newtonian/default.json' --model_path 'output/pacnerf/non_newtonian/0' --source_path '/home/qingran/Desktop/gic/data/pacnerf/non_newtonian/0' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/non_newtonian/0/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/non_newtonian/default.json' --model_path 'output/pacnerf/non_newtonian/1' --source_path '/home/qingran/Desktop/gic/data/pacnerf/non_newtonian/1' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/non_newtonian/1/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/non_newtonian/default.json' --model_path 'output/pacnerf/non_newtonian/2' --source_path '/home/qingran/Desktop/gic/data/pacnerf/non_newtonian/2' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/non_newtonian/2/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/non_newtonian/default.json' --model_path 'output/pacnerf/non_newtonian/3' --source_path '/home/qingran/Desktop/gic/data/pacnerf/non_newtonian/3' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/non_newtonian/3/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/non_newtonian/default.json' --model_path 'output/pacnerf/non_newtonian/4' --source_path '/home/qingran/Desktop/gic/data/pacnerf/non_newtonian/4' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/non_newtonian/4/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/non_newtonian/default.json' --model_path 'output/pacnerf/non_newtonian/5' --source_path '/home/qingran/Desktop/gic/data/pacnerf/non_newtonian/5' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/non_newtonian/5/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/non_newtonian/default.json' --model_path 'output/pacnerf/non_newtonian/6' --source_path '/home/qingran/Desktop/gic/data/pacnerf/non_newtonian/6' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/non_newtonian/6/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/non_newtonian/default.json' --model_path 'output/pacnerf/non_newtonian/7' --source_path '/home/qingran/Desktop/gic/data/pacnerf/non_newtonian/7' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/non_newtonian/7/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/non_newtonian/default.json' --model_path 'output/pacnerf/non_newtonian/8' --source_path '/home/qingran/Desktop/gic/data/pacnerf/non_newtonian/8' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/non_newtonian/8/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/non_newtonian/default.json' --model_path 'output/pacnerf/non_newtonian/9' --source_path '/home/qingran/Desktop/gic/data/pacnerf/non_newtonian/9' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/non_newtonian/9/0.ply