# python train_fixed_gs.py --config_path 'config/pacnerf/sand/default.json' --model_path 'output/pacnerf/sand/0' --source_path '/home/qingran/Desktop/gic/data/pacnerf/sand_batch/0' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/sand/0/0.ply

python train_fixed_gs.py --config_path 'config/pacnerf/plasticine/default.json' --model_path 'output/pacnerf/plastic/0' --source_path '/home/qingran/Desktop/gic/data/pacnerf/plasticine_batch/0' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/plasticine/0/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/plasticine/default.json' --model_path 'output/pacnerf/plastic/1' --source_path '/home/qingran/Desktop/gic/data/pacnerf/plasticine_batch/1' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/plasticine/1/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/plasticine/default.json' --model_path 'output/pacnerf/plastic/2' --source_path '/home/qingran/Desktop/gic/data/pacnerf/plasticine_batch/2' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/plasticine/2/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/plasticine/default.json' --model_path 'output/pacnerf/plastic/3' --source_path '/home/qingran/Desktop/gic/data/pacnerf/plasticine_batch/3' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/plasticine/3/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/plasticine/default.json' --model_path 'output/pacnerf/plastic/4' --source_path '/home/qingran/Desktop/gic/data/pacnerf/plasticine_batch/4' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/plasticine/4/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/plasticine/default.json' --model_path 'output/pacnerf/plastic/5' --source_path '/home/qingran/Desktop/gic/data/pacnerf/plasticine_batch/5' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/plasticine/5/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/plasticine/default.json' --model_path 'output/pacnerf/plastic/6' --source_path '/home/qingran/Desktop/gic/data/pacnerf/plasticine_batch/6' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/plasticine/6/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/plasticine/default.json' --model_path 'output/pacnerf/plastic/7' --source_path '/home/qingran/Desktop/gic/data/pacnerf/plasticine_batch/7' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/plasticine/7/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/plasticine/default.json' --model_path 'output/pacnerf/plastic/8' --source_path '/home/qingran/Desktop/gic/data/pacnerf/plasticine_batch/8' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/plasticine/8/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/plasticine/default.json' --model_path 'output/pacnerf/plastic/9' --source_path '/home/qingran/Desktop/gic/data/pacnerf/plasticine_batch/9' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/plasticine/9/0.ply




python train_fixed_gs.py --config_path 'config/pacnerf/elastic/default.json' --model_path 'output/pacnerf/elastic/0' --source_path '/home/qingran/Desktop/gic/data/pacnerf/elastic/0' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/elastic/0/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/elastic/default.json' --model_path 'output/pacnerf/elastic/1' --source_path '/home/qingran/Desktop/gic/data/pacnerf/elastic/1' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/elastic/1/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/elastic/default.json' --model_path 'output/pacnerf/elastic/2' --source_path '/home/qingran/Desktop/gic/data/pacnerf/elastic/2' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/elastic/2/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/elastic/default.json' --model_path 'output/pacnerf/elastic/3' --source_path '/home/qingran/Desktop/gic/data/pacnerf/elastic/3' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/elastic/3/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/elastic/default.json' --model_path 'output/pacnerf/elastic/4' --source_path '/home/qingran/Desktop/gic/data/pacnerf/elastic/4' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/elastic/4/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/elastic/default.json' --model_path 'output/pacnerf/elastic/5' --source_path '/home/qingran/Desktop/gic/data/pacnerf/elastic/5' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/elastic/5/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/elastic/default.json' --model_path 'output/pacnerf/elastic/6' --source_path '/home/qingran/Desktop/gic/data/pacnerf/elastic/6' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/elastic/6/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/elastic/default.json' --model_path 'output/pacnerf/elastic/7' --source_path '/home/qingran/Desktop/gic/data/pacnerf/elastic/7' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/elastic/7/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/elastic/default.json' --model_path 'output/pacnerf/elastic/8' --source_path '/home/qingran/Desktop/gic/data/pacnerf/elastic/8' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/elastic/8/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/elastic/default.json' --model_path 'output/pacnerf/elastic/9' --source_path '/home/qingran/Desktop/gic/data/pacnerf/elastic/9' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/elastic/9/0.ply

python train_fixed_gs.py --config_path 'config/pacnerf/sand/default.json' --model_path 'output/pacnerf/sand/1' --source_path '/home/qingran/Desktop/gic/data/pacnerf/sand_batch/1' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/sand/1/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/sand/default.json' --model_path 'output/pacnerf/sand/2' --source_path '/home/qingran/Desktop/gic/data/pacnerf/sand_batch/2' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/sand/2/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/sand/default.json' --model_path 'output/pacnerf/sand/3' --source_path '/home/qingran/Desktop/gic/data/pacnerf/sand_batch/3' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/sand/3/0.ply
python train_fixed_gs.py --config_path 'config/pacnerf/sand/default.json' --model_path 'output/pacnerf/sand/4' --source_path '/home/qingran/Desktop/gic/data/pacnerf/sand_batch/4' --sim_ini_pcd_path /home/qingran/Downloads/simulation_data/sand/4/0.ply

